# -*- coding: utf-8 -*-
"""cse220 lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9txC8V3ATnDahgyr2N20WfJunbhTeyE
"""

import numpy as np
arr = np.array([[1, 2, 3, 4], [10, 2, 3, 4], [9, 4, 1, 5]])#making matrix from a array
print(arr)  # Prints the array
print(arr.shape)#(3,4)=tuppe e diche(row,col)
row, col = arr.shape  # Unpacking of tupple.. row,col=(3,4)
print(row, col)#3,4
sum=0
for i in range(row):
  for j in range(col):
    if i==0 and j==1:
     sum+=arr[i][j]#arr[0][1]=arr[row][col]=2##matrix theke bujha jay
print(sum)

# Task 01: Zigzag Walk
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def walk_zigzag(floor):
  row,col=floor.shape
  if row%2!=0:#5=row
    for c in range(col):
      if c%2==0:#4=col
        for r in range(0,row,2):
          print(floor[r][c],end=" ")
        print()
      else:
        for r in range(row-2,0,-2):
          print(floor[r][c],end=" ")
        print()
  else:#row=6
    for c in range(col):
      if c%2==0:#4=col
        for r in range(0,row-1,2):
          print(floor[r][c],end=" ")
        print()
      else:
        for r in range(row-1,0,-2):
          print(floor[r][c],end=" ")
        print()
#DO NOT CHANGE THE CODE BELOW
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )
print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

#task1
# Task 01: Zigzag Walk
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def walk_zigzag(floor):
  #TO DO
  row,col=floor.shape
  for i in range(col):
    if row%2!=0:
      if i%2==0:
        for j in range(0,row,2):
          print(floor[j][i],end=" ")
      else:
        for j in range(row-2,0,-2):
          print(floor[j][i],end=" ")
    else:
        if i%2==0:
          for j in range(0,row,2):
            print(floor[j][i],end=" ")
        else:
          for j in range(row-1,0,-2):
            print(floor[j][i],end=" ")
    print('\n')
#DO NOT CHANGE THE CODE BELOW
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )
print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

#task5
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def play_game(arena):
    row, col = arena.shape
    total_points=0
    for r in range(row):
      point=0
      for c in range(col):
        if arena[r][c]!=0 and arena[r][c]%50==0:
          if r!=0 and arena[r-1][c]==2:
            point+=1
          if r!=row-1 and arena[r+1][c]==2:
            point+=1
          if c!=0 and arena[r][c-1]==2:
            point+=1
          if c!=col-1 and arena[r][c+1]==2:
            point+=1
      total_points+=(2*point)
    print(f"Points Gained: {total_points}.", end=" ")
    if total_points>= 10:
        print("Your team has survived the game.")
    else:
        print("Your team is out.")
arena = np.array([[0, 2, 2, 0],
                  [50, 1, 2, 0],
                  [2, 2, 2, 0],
                  [1, 100, 2, 0]])
print_matrix(arena)
play_game(arena)
print(".....................")

arena = np.array([[0, 2, 2, 0, 2],
                  [1, 50, 2, 1, 100],
                  [2, 2, 2, 0, 2],
                  [0, 200, 2, 0, 0]])
print_matrix(arena)
play_game(arena)

#task5
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def play_game(arena):
    rows, cols = arena.shape
    total_points = 0
    for i in range(rows):
      for j in range(cols):
        points=0
        if arena[i][j] % 50 == 0 and arena[i][j] != 0:#0%0==0
                if i > 0 and arena[i-1][j] == 2:#up chqing.... corner chqing
                    points += 1
                if i < rows - 1 and arena[i+1][j] == 2:#down chqing
                    points += 1
                if j > 0 and arena[i][j-1] == 2:
                    points += 1
                if j < cols - 1 and arena[i][j+1] == 2:
                    points += 1
        total_points += points * 2
    print(f"Points Gained: {total_points}.", end=" ")
    if total_points>= 10:
        print("Your team has survived the game.")
    else:
        print("Your team is out.")
arena = np.array([[0, 2, 2, 0],
                  [50, 1, 2, 0],
                  [2, 2, 2, 0],
                  [1, 100, 2, 0]])
print_matrix(arena)
play_game(arena)
print(".....................")

arena = np.array([[0, 2, 2, 0, 2],
                  [1, 50, 2, 1, 100],
                  [2, 2, 2, 0, 2],
                  [0, 200, 2, 0, 0]])
print_matrix(arena)
play_game(arena)

#Task 02: #linear array blle list create krbo just
import numpy as np
def decrypt_matrix(matrix):
    row, col = matrix.shape
    colsum = [0] * col#created list for linear array. evabe krbo alws.. if col=3 then column_sums = [0,0,0]
    for j in range(col):
        col_sum = 0
        for i in range(row):  # Iterate over rows
            col_sum += matrix[i][j]#prottek colum er sob value sum krtese
        colsum[j] = col_sum#idx onujai list er elem replace hoche.. when j=0 then colsums = [29, 0, 0] idx=0 te 0 replaced by 29
  #column_sums=[29, 16, 17]
    decrypted_array = [0] * (col - 1)#The size of decrypted_array is one less than the number of columns.
    #initially ..decrypted_array = [0, 0]
    for k in range(col - 1):
        decrypted_array[k] = colsum[k + 1] - colsum[k]
    return decrypted_array
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([[1,3,1],
                 [6,4,2],
                 [5,1,7],
                 [9,3,3],
                 [8,5,4]
                 ])
returned_array=decrypt_matrix(matrix)
print(returned_array)
#This should print [-13, 1]

#intersection
import numpy as np
def decrypt_matrix(matrix):
  row=len(matrix)
  col=len(matrix[0])
  c=int((col//2))
  r=int((row//2))
  return matrix[r][c]
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 5, 8, 9],
    [1, 3, 5, 7, 9]])
returned_array=decrypt_matrix(matrix)
print(returned_array)
#This should print 5

#smalest value's com summation print
import numpy as np
def decrypt_matrix(matrix):
  row=len(matrix)
  col=len(matrix[0])
  min=0
  c=0
  for i in matrix:#########################
    print(i)
  for r in range(row):
    for c in range(col):
      if matrix[r][c]<min:
        min=matrix[r][c]
  for r in range(row):
    for co in range(col):
      if min==matrix[r][co]:
        c=co
        break
  sum=0
  for r in range(row):
    for co in range(col):
       if c==co:
         sum+=matrix[r][co]
  return sum
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([
    [3, 8, 9],
    [4, 2, 7],
    [5, 6, 1]])
returned_array=decrypt_matrix(matrix)
print(returned_array)
#This should print 17

import numpy as np
def decrypt_matrix(matrix):
  row=len(matrix)
  col=len(matrix[0])
  nr=int(row//2)
  for r in range(row):
    if r==nr:
     for c in range(1):
       matrix[r][0],matrix[r][col-1]=matrix[r][col-1],matrix[r][0]
      #  lc=matrix[r][0]
      #  matrix[r][0]=matrix[r][col-1]
      #  matrix[r][col-1]=lc
       #matrix[r][col-1] = matrix[r][lc]xxxxxxxx cause lc is value and its=4.. out of index, we just want place the value bt we r using value as idx
  return matrix
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([
    [3, 8, 9],
    [4, 2, 7],
    [5, 6, 1]])
returned_array=decrypt_matrix(matrix)
print(returned_array)

def decrypt_matrix(matrix):
  row=len(matrix)
  col=len(matrix[0])
  min=0
  c=0
  for r in range(row):
    for c in range(col):
      if matrix[r][c]<min:
        min=matrix[r][c]
  for r in range(row):
    for co in range(col):
      if min==matrix[r][co]:
        c=co
        break
  sum=0
  for r in range(row):
    for co in range(col):
       if c==co:
         sum+=matrix[r][co]
  return sum
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([
    [3, 8, 9],
    [4, 2, 7],
    [5, 6, 1]])
returned_array=decrypt_matrix(matrix)
print(returned_array)

# Task 03: right Row Rotation or down ward jokhon chole matrix e
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def row_rotation(exam_week, seat_status):
  row,col=seat_status.shape
  for i in range(exam_week-1):
    temp=np.array(seat_status[len(seat_status)-1])#new array create holo np.array deate
    #print(temp) #['Z' , 'AA' , 'BB' , 'CC' , 'DD']
    #last row ta temp e array hisebe save krlam cz 1st rotation e
    for j in range(row-1,0,-1):
      seat_status[j]=seat_status[j-1] #matrix[j]=row,matrix[j][i]=element... j=row,i=col
     #when j=0, seat_status[j]=['Z' , 'AA' , 'BB' , 'CC' , 'DD'] and seat_status[j-1]=['U' , 'V' , 'W' , 'X' , 'Y']
     #seat_status[j]=['U' , 'V' , 'W' , 'X' , 'Y'] hoe galo jokhon j=0
     #bt ekhane last row ta haraye jache bt upore temp e ami last row save rakhsi
    seat_status[0]=temp#akdom last row ta 1st row te bosbe
    #print(seat_status[0])
  print(seat_status)
  return (len(seat_status)-1)%exam_week #size of array, not the length of array thats why len(seat_status)-1=6-1=5
seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'], #this array len=6 and size=5
                  ['F' , 'G' , 'H' , 'I' , 'J'],#array er vitore array=2D array, list er vitore elem o list. evabe think
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])#list array te convert hoche just
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation and return the row number
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

# Task 03: right Row Rotation or down ward jokhon chole matrix e
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def row_rotation(exam_week, seat_status):
  row,col=seat_status.shape
  for r in range(exam_week-1):
    temp=np.array(seat_status[0])
    for i in range(0,row-1,1):
      seat_status[i]=seat_status[i+1]
    seat_status[len(seat_status)-1]=temp
  print(seat_status)
  for r in range(row):
    for c in range(col):
      if seat_status[r][c]=='AA':
        return r+1 #r is 0 based index thats y added 1
seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'], #this array len=6 and size=5
                        ['F' , 'G' , 'H' , 'I' , 'J'],#array er vitore array=2D array, list er vitore elem o list. evabe think
                        ['K' , 'L' , 'M' , 'N' , 'O'],
                        ['P' , 'Q' , 'R' , 'S' , 'T'],
                        ['U' , 'V' , 'W' , 'X' , 'Y'],
                        ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])#list array te convert hoche just
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation and return the row number
print(f'Your friend AA will be on row {row_number}')

# Task 03:   left rotation of matric or 2D array or upward jokhon chole matrix e
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def row_rotation(exam_week, seat_status):
  row,col=seat_status.shape
  for i in range(exam_week-1):
    temp=np.array(seat_status[0])
    for r in range(row-1):
      seat_status[r]=seat_status[r+1]
    seat_status[len(seat_status)-1]=temp
  print(seat_status)
  row_number=(len(seat_status)-1)%exam_week
  return row_number
seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'], #this array len=6 and size=5
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])#list array te convert hoche just
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation and return the row number
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row

#Task 04: Matrix Compression row and col will always be even
#General Formula for Compressed Matrix Size:
#For an M×N matrix:
#The compressed matrix will have dimensions:
#(M//2,N//2)= this will be the compressed matrix row and col number
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def compress_matrix(mat):#mat=matrix
  #TO DO
  row,col=mat.shape
  #sum=0
  out=np.zeros((row//2,col//2),dtype=int)#new 2d array/matrix create. jekhane element sob=0
  #print(out) #print krle dkhbo sb elem=0
  outr=0
  for r in range(0,row,2):
    outc=0
    for c in range(0,col,2):
      sum=mat[r][c]+mat[r][c+1]+mat[r+1][c]+mat[r+1][c+1]
      out[outr][outc]=sum
      outc+=1
    outr+=1
  return out
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print("...............")
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print

#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def compress_matrix(mat):#mat=matrix
  row,col=mat.shape

#DO NOT CHANGE THE CODE BELOW
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print("...............")
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print

#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

#Task 04: Matrix Compression for 4x6
#so for in compressed matrix the row number=4//2=2 and col number=6//2=3
#so the compressed matrix=2x3
import numpy as np
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str, row)))
def compress_matrix(mat):
  #TO DO

  return out
#DO NOT CHANGE THE CODE BELOW
matrix=np.array([[1,2,3,4,10,11],
                 [5,6,7,8,12,13],
                 [1,3,5,2,14,15],
                 [-2,0,6,-3,15,17]
                 ])
print_matrix(matrix)
print("...............")
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print

#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------