# -*- coding: utf-8 -*-
"""cse220 lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqaPjt8Dp2yMU1g_EhU6Y9MJtGk8CpER
"""

#task3
class Node:#1
   def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next
def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return head
def printLinkedList(head):
    temp=head
    while temp!=None:
      if temp.next==None:
        print(temp.elem)
      else:
        print(temp.elem,end="-->")
      temp=temp.next
def check_similar(building_1, building_2):
   current1=building_1#head node location of building_1
   current2=building_2# head node location of building_2
   b=False
   c1=0
   c2=0
   while current1!=None:
      c1+=1
      current1=current1.next
   while current2!=None:
      c2+=1
      current2=current2.next
   current1=building_1 # cz uporer while er jnno current1=head r nei. akhn current1=last node ase. ti abar current1=head banailam
   current2=building_2
   while current1!=None and current2!=None:
     if c1!=c2:
       b=False
       break
     elif current1.elem==current2.elem:
       b=True
     else:
       b=False
       break
     current1=current1.next
     current2=current2.next
   if b==True:
      return 'Similar'
   else:
      return 'Not Similar'
#No need for np.array(), use a normal list
building_1 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green'])
building_2 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green','Blue'])
print('Building 1: ', end=' ')
printLinkedList(building_1)#building_1 is the location of head of the linked list. not the whole link list location. cz object=linklist means
#object=the location of head of the linked list, not the whole link list.. from this head we used the ther nodes
print('Building 2: ', end=' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value)

#task3
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next
def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return head
def printLinkedList(head):
    temp = head
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next
    print()
def check_similar(building_1, building_2):
  a=building_1
  b=building_2
  c1=0
  c2=0
  while a!=None:
    a=a.next
    c1+=1
  while b!=None:
    b=b.next
    c2+=1
  a=building_1
  b=building_2
  flag=True
  if c1!=c2:
    return 'Not Similar'
  else:
    while a!=None and b!=None:
      if a.elem==b.elem:
        pass
      else:
        flag=False
      a=a.next
      b=b.next
  return 'Similar'
print('==============Test Case 1=============')
building_1 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green'])
building_2 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green'])
print('Building 1: ', end=' ')
printLinkedList(building_1)
print('Building 2: ', end=' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)#returned_value=not similar
print(returned_value)
print()

#task4
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next
def assemble_conga_line(conga_line):
  current=conga_line
  b=True
  while current.next!=None:
    if current.elem<=current.next.elem: #for test 3, 41,41 sei case eo jate True ashe ti
    #for test1 loop sequence 1) current.elem=10<current.next.elem=15, 2)15<34, 3)34<41, 4)41<56, 5)56<72
      b=True
    else:
      b=False
      break
    current=current.next
  if b==True:
    return b
  else:
    return b
print('==============Test Case 1=============')
conga_line = createList([10,15,34,41,56,72])
print('Original Conga Line: ', end = ' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value) #This should print True
print()
print('==============Test Case 2=============')
conga_line = createList([10,15,44,41,56,72])
print('Original Conga Line: ', end = ' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value) #This should print False
print()
print('==============Test Case 2=============')
conga_line = createList([10,15,34,41,41,56,72])
print('Original Conga Line: ', end = ' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value) #This should print True
print()

#task4
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    if not arr:
        return None
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next
def assemble_conga_line(conga_line):
    current = conga_line
    while current.next is not None: #when current=72(last node for test1) node then current.next=None. so loop e dhukbena tkhn r. thats mean last node e aslei r loop e dhukbena
        if current.elem > current.next.elem:
            return False
        current = current.next
    return True
# Test Case 1
print('==============Test Case 1=============')
conga_line = createList([10, 15, 34, 41, 56, 72])
print('Original Conga Line: ', end=' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value)  # Expected: True
print()

# Test Case 2
print('==============Test Case 2=============')
conga_line = createList([10, 15, 44, 41, 56, 72])  # Removed np.array()
print('Original Conga Line: ', end=' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value)  # Expected: False
print()

#task4
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    if not arr:
        return None
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next

def assemble_conga_line(conga_line):
    if conga_line is None or conga_line.next is None:
        return True  # A single node or empty list is considered sorted

    current = conga_line
    while current.next is not None:
        if current.elem > current.next.elem:
            return False
        current = current.next
    return True

# Test Case 1
print('==============Test Case 1=============')
conga_line = createList([10, 15, 34, 41, 56, 72])
print('Original Conga Line: ', end=' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value)  # Expected: True
print()

# Test Case 2
print('==============Test Case 2=============')
conga_line = createList([10, 15, 44, 41, 56, 72])  # Removed np.array()
print('Original Conga Line: ', end=' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value)  # Expected: False
print()

#task4 xxxxxxxxxxxxxx
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" -->")
        else:
            print(temp.elem)
        temp = temp.next
def assemble_conga_line(conga_line):
  current=conga_line
  b=True
  while current!=None:
    if current.elem>current.next.elem: #when current=last node(72). then current.next=None. tokhon current.next.elem=kisu ni ti error diche
      b=False
    else:
      b=True
    current=current.next
  if b==True:
    return b
  else:
    return b
print('==============Test Case 1=============')
conga_line = createList([10,15,34,41,56,72])
print('Original Conga Line: ', end = ' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value) #This should print True
print()
print('==============Test Case 2=============')
conga_line = createList(np.array([10,15,44,41,56,72]))
print('Original Conga Line: ', end = ' ')
printLinkedList(conga_line)
returned_value = assemble_conga_line(conga_line)
print(returned_value) #This should print False
print()

#task1
import numpy as np
def mergeSortedArray(arr1, arr2):
 idxarr1=0
 idxarr2=0
 idxmerged=0
 newarr=np.zeros(len(arr1)+len(arr2),dtype=int)
 while idxarr1<len(arr1) and idxarr2<len(arr2):
   if arr1[idxarr1]==arr2[idxarr2]:
     newarr[idxmerged]=arr1[idxarr1]
     idxarr1+=1
     #idxarr2+=1
     idxmerged+=1
   if arr1[idxarr1]<arr2[idxarr2]:
     newarr[idxmerged]=arr1[idxarr1]
     idxarr1+=1
     idxmerged+=1
   elif arr1[idxarr1]>arr2[idxarr2]:
     newarr[idxmerged]=arr2[idxarr2]
     idxarr1+=1
     idxmerged+=1
 if idxarr1<len(arr1):
  while idxarr1<len(arr1):
    newarr[idxmerged]=arr1[idxarr1]
    idxarr1+=1
    idxmerged+=1
 if idxarr2<len(arr2):
  while idxarr2<len(arr2):
    newarr[idxmerged]=arr2[idxarr2]
    idxarr2+=1
    idxmerged+=1
 return newarr
a1 = np.array([1, 2, 3])
print(f'Sorted Array 1: {a1}')
a2 = np.array([2, 5, 6])
print(f'Sorted Array 2: {a2}')
returned_value = mergeSortedArray(a1, a2)
print(f'Merged Sorted Array: {returned_value}\n') # This should print [1, 2, 2, 3, 5, 6]
print('\n==================================\n')

a3 = np.array([1, 3, 5, 11])
print(f'Sorted Array 3: {a3}')
a4 = np.array([2, 7, 8])
print(f'Sorted Array 4: {a4}')
returned_value = mergeSortedArray(a3, a4)
print(f'Merged Sorted Array: {returned_value}\n')

#task5
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    if not arr:
        return None
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next
def sum_dist(head, arr):
   sum=0
   head1=head
   c=0
   for i in arr:
     while head1!=None:
       if c==i:
         sum+=head1.elem
       head1=head1.next
       c+=1
     c=0
     head1=head
   return sum
#######################
print('==============Test Case 1=============')
LL1 = createList([10,16,-5,9,3,4])
dist =[2,0,5,2,8]
returned_value = sum_dist(LL1, dist)
print(f'Sum of Nodes: {returned_value}') #This should print Sum of Nodes: 4
print()

#task5
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    if not arr:
        return None
    conga_line = Node(arr[0])
    tail = conga_line
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return conga_line

def printLinkedList(conga_line):
    temp = conga_line
    while temp is not None:
        if temp.next is not None:
            print(temp.elem, end=" --> ")
        else:
            print(temp.elem)
        temp = temp.next
def sum_dist(head, arr):
   tail=head
   c=0
   sum=0
   while tail!=None:
     for i in arr:
       if i==c:
         sum+=(tail.elem)
     tail=tail.next
     c+=1
   return sum
print('==============Test Case 1=============')
LL1 = createList([10,16,-5,9,3,4])
dist =[2,0,5,2,8]
returned_value = sum_dist(LL1, dist)
print(f'Sum of Nodes: {returned_value}') #This should print Sum of Nodes: 4
print()

#task2
def mostWater(arr):
    left = 0
    right = len(arr) - 1
    maxarea = 0
    while left < right:
        min_height = min(arr[left], arr[right])
        area = min_height * (right - left)
        maxarea = max(maxarea, area)
        if arr[left] < arr[right]:
            left += 1
        else:
            right -= 1
    return maxarea
height = np.array([1, 8, 6, 2, 5, 4, 8, 3, 7]).tolist()
print(f'Given Array: {height}')
print(f'\nExpected Output: 49')
print(f'Your Output: {mostWater(height)}')