# -*- coding: utf-8 -*-
"""cse220 lab7 BST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_dWz8E0q0oIF4lKybZ65De8rtQPtQsC
"""

class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

def inorder(root):
  if root == None:
    return

  inorder(root.left)
  print(root.elem, end = ' ')
  inorder(root.right)

def tree_construction(arr, i = 1):
  if i>=len(arr) or arr[i] == None:
    return None
  p = BTNode(arr[i])
  p.left = tree_construction(arr, 2*i)
  p.right = tree_construction(arr, 2*i+1)
  return p


root2 = tree_construction([None, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', None, None, None, 'I', 'J', None, 'k'])
inorder(root2)

"""Task 1"""

def LCA(root, x, y):
  #To Do
    if root is None:
        return None

    # If either x or y is equal to root, root is the LCA
    if root.elem == x or root.elem == y:
        return root

    # Search in left and right subtrees
    left_lca = LCA(root.left, x, y)
    right_lca = LCA(root.right, x, y)

    # If x and y are found in different subtrees
    if left_lca and right_lca:
        return root

    # Otherwise, return the non-None child
    return left_lca if left_lca else right_lca


#DRIVER CODE
root = BTNode(15)
root.left = BTNode(10)
root.left.left = BTNode(8)
#Write by yourself from the given tree (Create parent node and its corresponding left and right children nodes)
#check all the sample inputs given
#You can take help by seeing the driver code of Lab-6

"""Task 2"""

def find_path(root, key):
  #To Do


#DRIVER CODE
#Write by yourself from the given tree
print(find_Path(root,15))
#This should print [30,10,15]

print(find_Path(root,50))
#This should print No Path Found

"""Task 3"""

def sum_of_leaves(root, sum):
  #To Do
    if root==None:
        return sum
    if root.left==None and root.right==None:
        sum += root.data
        return sum
    sum = sum_of_leaves(root.left, sum)
    sum = sum_of_leaves(root.right, sum)
    return sum

#DRIVER CODE
#Write by yourself from the given tree

print(sum_of_leaves(root, 0))

"""Task 4"""

def mirror_sum(root):
  #To Do

#DRIVER CODE

print("---------------------Test#1---------------------")
#Example Tree 1
root = BTNode(10)
n1 = BTNode(6)
n2 = BTNode(15)
n3 = BTNode(3)
n4 = BTNode(8)
n5 = BTNode(12)
n6 = BTNode(20)

root.left = n1
root.right = n2

n1.left = n3
n1.right = n4

n2.left = n5
n2.right = n6
print("Expected Output: 64")
print("You output     :",mirror_sum(root))

print("---------------------Test#2---------------------")

#Example Tree 1
root = BTNode(20)
n1 = BTNode(15)
n2 = BTNode(25)
n3 = BTNode(10)
n4 = BTNode(18)
n5 = BTNode(5)
n6 = BTNode(30)

root.left = n1
root.right = n2

n1.left = n3
n1.right = n4

n3.left = n5
n2.right = n6
print("Expected Output: 80")
print("You output     :",mirror_sum(root))