# -*- coding: utf-8 -*-
"""cse220 recursion practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVSsn_PdMJUEGzi-IVGF008lvDKVradl

# Singly Linked List Creation
"""

class Node:
  def __init__(self, val, next):
    self.val=val
    self.next=next

class LinkedList:
  # head=None
  def __init__(self,l1):
    self.head= Node(l1[0], None)
    n1=self.head
    # print(n1.val)
    for i in l1[1:]:
      n2= Node(i, None)
      n1.next=n2
      n1=n2

  def getHead(self):
    return self.head

ll1= LinkedList([5,10,15,-5,12])
head= ll1.getHead()

#1.1 Forward Printing a singly linkled list values using iteration

def iterativePrintList(head):
  while(head!=None):
    print(head.val)
    head=head.next

iterativePrintList(head)

"""**1.2 ForwardPrinting a singly linkled list values using recursion**"""

def recursiveForwardPrintList(head):
  if head!=None:#ni base case
    print(head.val)
    recursiveForwardPrintList(head.next)

recursiveForwardPrintList(head)

def recursiveForwardPrintList(head):
  if head==None:#ni base case

  recursiveForwardPrintList(head.next)

recursiveForwardPrintList(head)

#alternate  5->10->15->-5->12
def recursiveForwardPrintList(head):
  if head==None:#base case
    return
  print(head.val)
  recursiveForwardPrintList(head.next)

recursiveForwardPrintList(head)

"""**2.1 Printing a singly linkled list values in reverse using iteration?**


**Not Possible!**

**2.2 Printing a singly linkled list values in reverse using recursion**
"""

def recursiveReversePrintList(head):#5->10->15->-5->12
  if head!=None:
    recursiveReversePrintList(head.next)
    print(head.val)

recursiveReversePrintList(head)

#alternate 5->10->15->-5->12
def recursiveReversePrintList(head):
  if head==None:#base case
    return
  recursiveReversePrintList(head.next)
  print(head.val)
recursiveReversePrintList(head)

"""**3.1 Calculation of exponenentiation without iteration/recursion**"""

def exp(base,power):
  return base**power

print(exp(5,3))

"""**3.2 Calculation of exponenentiation using iteration**"""

def exp_iteration(base,power):
  res=base
  for i in range(power-1):    # i=0,1
    res*=base
  return res
print(exp_iteration(5,3))

"""**3.3 Calculation of exponenentiation using recursion**"""

def exp_recursion(base,power):
  if power==0:
    return 1
  else:
    return base*exp_recursion(base,power-1)
print(exp_recursion(5,3))

"""**4.1 Length of a linked list using iterations**"""

def iterativeLinkedListLength(head):
  length=0
  while head!=None:
    length+=1
    head=head.next
  return length

print(iterativeLinkedListLength(head))

"""**4.2 Length of a linked list using recursion**"""

def recursiveLinkedListLength(head): #xxxxxxxxxxxx
  if(head==None):
    return #it will return None
  else:
    return 1+recursiveLinkedListLength(head.next) #when if condition e dhukbe tokhon 1+ None hbe. which is a non type error. int+str addition. which is incorrect in summation

print(recursiveLinkedListLength(head))

def recursiveLinkedListLength(head):#5->10->15->-5->12
 if head==None:
  return 0
 return 1+recursiveLinkedListLength(head.next)#head er count asei. ti 1+ krsi. cz next func call hoche/count hoche head.next theke

print(recursiveLinkedListLength(head))

"""**5.1 Factorial Calculation using iteration**"""

def iterative_factorial(num):
  fac=1
  for i in range(num,0,-1):
    fac=fac*i
  return fac

print(iterative_factorial(5))

"""**5.2 Factorial Calculation using recursion**"""

def recursive_factorial(num):
  if (num==0):
    return 1
  else:
    return num*recursive_factorial(num-1)

print(recursive_factorial(5))

"""**6.1 First nth Fibonacci number printing using iteration**"""

def iterative_fibonacci(num):
  p= 0
  q= 1
  print(p)
  print(q)
  for i in range(num-2):
    r=p+q
    print(r)
    p=q
    q=r

iterative_fibonacci(8)

"""**6.2 First nth Fibonacci number printing using recursion**"""

def recursive_fibonacci(num):
  if (num==0 or num==1):
    return num
  else:
    return recursive_fibonacci(num-1)+recursive_fibonacci(num-2)

for i in range(8):
  print(recursive_fibonacci(i))

"""This recursive_fibonacci method can find one fibonacci number
at a time. That is why we are using a loop to call it repeatedly"""

"""7.1 Print the element of the last node using iteration [HW]"""

def last_element_iterative(head):
  #Your Code Here
  if (head.next==None):
    print(head.val)
  else:
    last_element_iterative(head.next)

last_element_iterative(head)

"""7.2 Print the element of the last node using recursion [HW]"""

def last_element_recursive(head):
  #Your Code Here
  if (head==None):
    pass
  else:
    if head.next==None:
      return head.val
    else:
      return last_element_recursive(head.next)

print(last_element_recursive(head))

"""8.1 Find the maximum number from a list using iteration"""

def max_iterative(list1):
  max=list1[0]
  for i in list1:
    if i>max:
      max=i
  return max

x= max_iterative([5,2,-3,1,0,8,7])
print(f"Maximum: {x}")

"""8.2 Find the maximum number from a list using recursion"""

def max_recursive(list1, n):
  if (n == 1):
    return list1[0]
  return max(list1[n - 1], max_recursive(list1, n - 1))

x= max_recursive([5,2,-3,1,0,8,7],7)
print(f"Maximum: {x}")

"""9.1 Find the sum of all even numbers of a list using iteration"""

def sum_iterative(list1):
  sum=0
  for i in list1:
    if i%2==0:
      sum+=i
  return sum

x= sum_iterative([5,2,-3,1,0,8,7])
print(f"Summation: {x}")

"""9.2 Find the sum of all even numbers of a list using recursion"""

def sum_recursive(list1):
  if len(list1)==0:
    return 0
  else:
    if list1[0]%2==0:
      return list1[0]+sum_recursive(list1[1:])
    else:
      return sum_recursive(list1[1:])
x= sum_recursive([5,2,-3,1,0,8,7])
print(f"Summation: {x}")

def sum_recursive(list1, i):
  if len(list1)== i:
    return 0
  else:
    if list1[i]%2==0:
      return list1[i]+sum_recursive(list1, i+1)
    else:
      return sum_recursive(list1, i+1)
x= sum_recursive([5,2,-3,1,0,8,7], 0)
print(f"Summation: {x}")

"""10.1 Decimal to Binary Conversion using iteration [HW]"""

def dec_to_bin_iterative(num):
  temporary= ""
  while num>1:
    n= num%2
    temporary+= str(n)
    num= num//2
  if num==1:
    temporary+= str(num)
  for i in range(len(temporary)-1,-1,-1):
    print(temporary[i], end='')

dec_to_bin_iterative(10)

"""10.2 Decimal to Binary Conversion using recursion [HW]"""

def dec_to_bin_recursive(n):
   if n > 1:
       dec_to_bin_recursive(n//2)
   print(n % 2,end = '')

dec_to_bin_recursive(10)

"""13.1 Binary Search using iteration"""

def binary_search_iterative(list1, elem):
  left=0
  right=len(list1)-1
  for i in range(len(list1)//2):
    mid=(left+right)//2
    if elem>list1[mid]:
      left= mid+1
    elif elem<list1[mid]:
      right= mid
    else:
      return f"Element found at index: {mid}"
  return f"Element not found"

print(binary_search_iterative([5,2,-3,1,0,8,7],8))

"""13.2 Binary Search using recursion"""

def binary_search_recursive(list1, elem, left, right):
  mid=(left+right)//2
  if elem>list1[mid]:
    return binary_search_recursive(list1, elem, mid+1, right)
  elif elem<list1[mid]:
    return binary_search_recursive(list1, elem, left, mid)
  elif elem==list1[mid]:
    return f"Element found at index: {mid}"
  #elif left==right and elem!=list1[mid]:
  elif elem!=list1[mid]:
    return f"Element not found"

print(binary_search_recursive([5,2,-3,1,0,8,7],8,0,6))
print(binary_search_recursive([5,2,-3,1,0,8,7],9,0,6))

"""11. Add all the elements of a linked list using recursion"""

def add_elem_recursive(head):
  if head== None:
    return 0
  else:
    return head.val+ add_elem_recursive(head.next)

print(add_elem_recursive(head))

"""12. Find the node with maximum element and

print the element using recursion
"""

def max_elem_recursive(head):
  if head== None:
    return 0
  else:
    return max(head.val, max_elem_recursive(head.next))


print(max_elem_recursive(head))

"""14. Reverse print a list using recursion

15. Selection sort of a list using recursion

16. Bubble sort of a list using recursion

17. Insertion sort of a list using recursion

14.1 Ternary search using iteration
"""

def binary_search_iterative(list1, elem):
  left=0
  right=len(list1)-1
  for i in range(len(list1)//2):
    mid1 = left + (right-left)//3
    mid2 = right - (right-left)//3
    if elem>list1[mid1]:
      left= mid1+1
    elif elem<list1[mid2]:
      right= mid2-1
    elif (elem==list1[mid1]):
      return f"Element found at index: {mid1}"
    elif (elem==list1[mid2]):
      return f"Element found at index: {mid2}"
  return f"Element not found"

print(binary_search_iterative([5,2,-3,1,0,8,7],8))

"""14.2 Ternary search using recursion [HW]"""

def ternary_search_recursive(list1, elem, left, right):















print(binary_search_recursive([5,2,-3,1,0,8,7],8))

"""13. Create a node with an element given and

add it at the end of a linked list
"""

def addNode(head, elem):
  if (head.next==None):
    head.next= Node(elem, None)
  else:
    addNode(head.next, elem)

addNode(head, 50)

"""14. Convert a linear linked list into circular using recursion"""

def lin_to_cir(head, n):
  if n.next==None:
    n.next=head
  else:
    lin_to_cir(head, n.next)

lin_to_cir(head, head)

"""15. Print a circular linked list recursively"""

def print_cir_ll_recursive(head, n, i):
  if (head==n and i==0) or head!=n:
    print(n.val)
    print_cir_ll_recursive(head, n.next, i+1)

print_cir_ll_recursive(head, head, 0)

"""16. Check whether a string is a palindrome or not recursively"""

def palindrome(s1, i, j):
  if (s1[i]==s1[j]) and i<j:
    palindrome(s1, i+1, j-1)
  elif (s1[i]!=s1[j]):
    print("Not a palindrome")
  elif i>=j:
    print("Palindrome")

s1="RACECAR"
palindrome(s1, 0, len(s1)-1)

"""17. Count the number of vowels in a string recursively"""

def vowels(s1,i):
  if (i==len(s1)):
    return 0
  elif s1[i] in "AEIOUaeiou":
    return 1+vowels(s1,i+1)
  elif s1[i] not in "AEIOUaeiou":
    return vowels(s1,i+1)

print(vowels("YOOO!damnthatguy",0))

"""18. Convert all the lower cases in a

string into upper case using recursion
"""

def lower_to_upper(s1,i):
  if i==len(s1):
    return ""
  elif (97<=ord(s1[i])<=122):
    return chr(ord(s1[i])-32) + lower_to_upper(s1, i+1)
  else:
    return s1[i]+ lower_to_upper(s1,i+1)

print(lower_to_upper("Yo! Whassup?", 0))

def mA(n):
  if(n>0):
    print(n)
    mA(n-1)

mA(10)