# -*- coding: utf-8 -*-
"""cse220 lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6H6lXMmI9m3d1OqWpWUQXfmSbUcKBD7
"""

#1
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next
def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head
def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()
def alternate_merge(head1, head2):
    temp1 = head1
    temp2 = head2
    while temp1!=None and temp2!=None:#11 and 4(actually temp2=4--1, 4 er poreo jehetu node ase so 4 theke last porjonto node temp2 te thakbe)
      c1=temp1.next#None
      c2=temp2.next#1
      temp1.next=temp2#11-4...(mainly=11-4-1) cz 4 er sthe 1 linked ase already.
      if c1==None:#now c1 None
         break
      temp2.next=c1#11-4-None########
      temp1=c1
      temp2=c2
    # if temp1==None and temp2!=None:xxxxxxxxx
    #   temp1.next=temp2# cz none.next=error. so temp1 er last node khujte hbe not none node. none node er sthe next e node add kra jayna
    return head1
print('==============Test Case 1=============')
head1 = createList([4,2,-2,4])
head2 = createList([8,6,5,-3,1])
print("Linked List 1:")
printLinkedList(head1)
print("Linked List 2:")
printLinkedList(head2)
head = alternate_merge(head1, head2)
print("Merged Linked List:")
printLinkedList(head)

#1
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next
def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head
def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()
def alternate_merge(head1, head2):
  temp1,temp2=head1,head2
  while temp1.next!=None and temp2.next!=None:
    cur1=temp1.next
    cur2=temp2.next
    temp1.next=temp2
    temp2.next=cur1
    temp1=cur1#None nei
    temp2=cur2#None nei
  if temp1.next==None and temp2.next!=None:
      temp1.next=temp2
  elif temp2.next==None and temp1.next!=None:
      temp2.next=temp1
  return head1
print('==============Test Case 1=============')
head1 = createList([4,2,-2,4])
head2 = createList([8,6,5,-3,1])
print("Linked List 1:")
printLinkedList(head1)
print("Linked List 2:")
printLinkedList(head2)
head = alternate_merge(head1, head2)
print("Merged Linked List:")
printLinkedList(head)

#node
class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next
def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head
def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()
def nodeAt(head1,idx):
  temp1=head1
  c=0
  while temp1!=None:
    if c==idx:
      return temp1
      break#break na dileo hoto cz ekbar return er por ar return krbena. so nicher line r kajer na
    c+=1
    temp1=temp1.next
  return None
def insert(head1,idx,elem):
  if idx==-1:
    newnode=Node(elem)
    newnode.next=head1
    return newnode
  temp1=head1
  x=nodeAt(head1,idx) #jei node er por newnode add hbe
  newnode=Node(elem)#newnode create
  newnode.next=x.next
  x.next=newnode
  return head1
def remove(head1,idx):
  if idx==0:
    head1=head1.next
    return head1
  else:
    x=nodeAt(head1,idx-1)
    x.next=x.next.next
    return head1
print('==============Test Case 1=============')
head1 = createList([1,2,6,8,11])
print("Linked List 1:")
printLinkedList(head1)
print(nodeAt(head1,2))#link node address
head=insert(head1,2,40)
printLinkedList(head)
head2=remove(head1,2)
printLinkedList(head2)