# -*- coding: utf-8 -*-
"""cse220 1st lecture

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yn1MYMYjpjFUFCxANRxTlaXzF8AH9_XX
"""

class Node:
  def __init__(self,elem,next=None):
    self.elem=elem
    self.next=next

class Node:
  def __init__(self,elem,next = None):
    self.elem,self.next = elem,next

  def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1,len(arr)):
      newNode = Node(arr[i])
      tail.next = newNode
      tail = newNode
    return head

  def printLinkedList(head):
    temp = head
    while temp != None:
      if temp.next != None:
        print(temp.elem, end = '-->')
      else:
        print(temp.elem)
      temp = temp.next
    print()
  def check_similar(building_1, building_2):
    #TO DO
    pass#remove this when writing this function
  #[DO NOT MODIFY THE TESTER CODES BELOW]
  #[THERE WILL BE 50% PENALTY IF IT'S MODIFIED]

  def check_similar(building_1, building_2):
      # Traverse both linked lists and compare their blocks
      current_1 = building_1
      current_2 = building_2

      # Traverse through both linked lists
      while current_1 is not None and current_2 is not None:
          if current_1.elem != current_2.elem:
              return "Not Similar"
          current_1 = current_1.next
          current_2 = current_2.next

      # If one list is longer than the other, they're not similar
      if current_1 is not None or current_2 is not None:
          return "Not Similar"

      return "Similar"
print('==============Test Case 1=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Similar'
unittest.output_test(returned_value, 'Similar')
print()
print('==============Test Case 2=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Yellow', 'Green']))#link list list create array theke
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()
print('==============Test Case 3=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green', 'Blue']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()
print('==============Test Case 4=============')
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green', 'Blue']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')
printLinkedList(building_1)
print('Building 2: ', end = ' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value) #This should print 'Not Similar'
unittest.output_test(returned_value, 'Not Similar')
print()

def get(head,index):
    c = 0

    n = head

    while n is not None:

        if c==index:

            return n.element

        c = c + 1

        n = n.next

    return -1

class Node:
    def __init__(self, elem, next = None):
        self.elem = elem
        self.next = next #next node er address
    def printLL(head):
        temp = head #ei head e head.next akhon r None na.
        while temp != None:#1->5->6->3->10->12->55->27->81->None #last node er pore none node thake.
        #ekhane temp.next!=None(eta mane last node ta bujhache. jar next means next node addresss None. cz er por r kono node ni) dile last node er elem print hotona.
            print(temp.elem)
            temp = temp.next #next n0de er adress
    def create_from_array(arr): #creating linked list from list
            if not arr: #arr er length/size jodi 0 na hoy. ekhane array er size 0 na. so if e dhukbena
                return
            head = Node(arr[0])#new obj create hoche Node cls er under e. ekhane head=Node(1). here elem=1,next=None.. creating node (head)
            tail = head#tail=Node(1)=head same #head ta store krtesi jate.
            for elem in arr[1:]:
                new_node = Node(elem)#obj create again under Node cls.new node e self.elem=5, self.next=None
                tail.next = new_node#tail.next.elem=5, tail.next.next=None, tail.next=new node(adress next node er)
                tail = new_node#tail=Node(5) here tail.elem=5 tail.next=None
            return head #head.elem=1, head.next=node 5 er address orthat st node holo 1 and tar next node holo 5 jar address
a = Node(10)
b = Node(25)
a.next = b#a er next e b node er address
c = Node(15)
b.next = c
d = Node(40)
c.next = d
head = a #head.elem=1, head.next=next node address of 5
arr = [1, 5, 6, 3, 10, 12, 55, 27, 81]
head = create_from_array(arr)#return head er
printLL(head)

arr = [1, 5, 6, 3, 10, 12, 55, 27, 81]
for elem in arr[1:]:
  print(elem)

class Node:
  def __init__(self.elem,next=None):
    self.elem=elem
    self.next=next
def creatlist(arr):
  head=Node(arr[0]) #head.elem='red', head.next=None
  tail=head #head ta new variable e rakhlam. jate ager line er main head ta nosto na hoy.
  for i in range(1,len(arr)):
    newNode=Node(arr[i])#node creat evabe hoy ti node creat krtesi bar bar loop chalaye
    tail.next=newNode
    tail=newNode
  return head #head akhn link list er mto hoe gese cz head.next=new node(1st node er porer node ase)
def

class Node:
  def __init__(self.elem,next=None):
    self.elem=elem
    self.next=next
def creatlist(arr):
  head=Node(arr[0]) #head.elem='red', head.next=None
  tail=head #head ta new variable e rakhlam. jate ager line er main head ta nosto na hoy.
  for i in range(1,len(arr)):
    newNode=Node(arr[i])#node creat evabe hoy ti node creat krtesi bar bar loop chalaye
    tail.next=newNode
    tail=newNode
  return head
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Yellow', 'Green']))
building_2 = createList(np.array(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green']))
print('Building 1: ', end = ' ')

#lab 1
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next

def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return head
def printLinkedList(head):
    temp=head
    while temp!=None:
      print(temp.elem,end="-->")
      temp=temp.next
    print()
# ✅ No need for np.array(), use a normal list
building_1 = createList(['Red', 'Green', 'Yellow', 'Red', 'Yellow', 'Green'])
building_2 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green'])
print('Building 1: ', end=' ')
printLinkedList(building_1)
print('Building 2: ', end=' ')
printLinkedList(building_2)

#lab 1
class Node: #1
   def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next
def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1, len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return head
def printLinkedList(head):
    temp=head
    while temp!=None:
      if temp.next==None:
        print(temp.elem)
      else:
        print(temp.elem,end="-->")
      temp=temp.next
def check_similar(building_1, building_2):
   current1=building_1#head node location of building_1
   current2=building_2# head node location of building_2
   b=False
   c1=0
   c2=0
   while current1!=None:
      c1+=1
      current1=current1.next
   while current2!=None:
      c2+=1
      current2=current2.next
   current1=building_1
   current2=building_2
   while current1!=None and current2!=None:
     if c1!=c2:
       b=False
       break
     if current1.elem==current2.elem:
       b=True
     else:
       b=False
       break
     current1=current1.next
     current2=current2.next
   if b==True:
      return 'Similar'
   else:
      return 'Not Similar'
#No need for np.array(), use a normal list
building_1 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green'])
building_2 = createList(['Red', 'Green', 'Yellow', 'Red', 'Blue', 'Green','Blue'])
print('Building 1: ', end=' ')
printLinkedList(building_1)#building_1 is the location of head of the linked list. not the whole link list location. cz object=linklist means
#object=the location of head of the linked list, not the whole link list.. from this head we used the ther nodes
print('Building 2: ', end=' ')
printLinkedList(building_2)
returned_value = check_similar(building_1, building_2)
print(returned_value)